<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string></string>
	<key>fileTypes</key>
	<array>
		<string>blip</string>
	</array>
	<key>foldingStartMarker</key>
	<string>\[\s*($|/\*(?!.*?\*/.*\S))</string>
	<key>foldingStopMarker</key>
	<string>^\s*\]</string>
	<key>keyEquivalent</key>
	<string>^~B</string>
	<key>name</key>
	<string>Blip</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#string-double</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#numeric-values</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#note-values</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.blip</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(%).*$\n?</string>
			<key>name</key>
			<string>comment.line.percent.blip</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.other.argument.waveform.blip</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(square|triangle|noise|sawtooth|sine)\b</string>
			<key>name</key>
			<string>constant.other.argument.waveform.blip</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.command.blip</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(a|r|s|p|pt|as|m|t|i|dc|d|st|at|rt|g|x|xb|w|v|pw|e|at|adsr|anv|vnv|pnv|dcnv)\b</string>
			<key>name</key>
			<string>keyword.command.blip</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.command.group.blip</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(instr|wave|grp|track)\b</string>
			<key>name</key>
			<string>keyword.command.group.blip</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.argument.blip</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([a-z\-\_]+)\b</string>
			<key>name</key>
			<string>variable.argument.blip</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>note-values</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.constant.blip</string>
						</dict>
					</dict>
					<key>match</key>
					<string>([cdefgabh]#?[0-9])\b</string>
					<key>name</key>
					<string>constant.other.note.blip</string>
				</dict>
			</array>
		</dict>
		<key>numeric-values</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.constant.blip</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\-?[0-9]+)\b</string>
					<key>name</key>
					<string>constant.numeric.blip</string>
				</dict>
			</array>
		</dict>
		<key>string-double</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.blip</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.blip</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.blip</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.blip</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.blip</string>
	<key>uuid</key>
	<string>7F01E9FE-1CCE-446B-BEE2-EEE23FBCE282</string>
</dict>
</plist>
