name: C

on:
  push:
    branches-ignore: [master]
  pull_request:
    branches: [master]

jobs:
  test_ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: install_dependencies
      run: |
        sudo apt-get update -y -qq
        sudo apt-get install libsdl2-dev
    - name: configure
      run: |
        ./autogen.sh
        ./configure
    - name: make
      run: make
    - name: make check
      run: make check
